openapi: 3.0.1
info:
  title: Credit Card Service API
  description: API para gestionar tarjetas de crédito.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Servidor local
paths:
  /cards:
    get:
      tags:
        - tarjeta
      summary: Listar tarjetas de crédito
      operationId: listCreditCards
      responses:
        '200':
          description: Lista de tarjetas de credito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreditCardResponse'
        'default':
          description: Error en la obtención de clientes
    post:
      tags:
        - tarjeta
      summary: Crear una nueva tarjeta de crédito
      operationId: registerCreditCard
      requestBody:
        description: Detalles de la nueva tarjeta de crédito
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreditCardRequest"
      responses:
        '200':
          description: Tarjeta creada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreditCardResponse"
        default:
          description: Error en la creacion de tarjeta de credito
  /cards/{id}:
    get:
      tags:
        - tarjeta
      summary: Obtener datos de una tarjeta de crédito
      operationId: getCreditCardById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tarjeta actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreditCardResponse"
        default:
          description: Error en obtener datos de la tarjeta de credito
    put:
      tags:
        - tarjeta
      summary: Actualizar una tarjeta de crédito
      operationId: updateCreditCard
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Detalles de la tarjeta de crédito actualizada
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreditCardRequest"
      responses:
        '200':
          description: Tarjeta actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreditCardResponse"
        default:
          description: Error en la actualización de tarjeta de credito
    delete:
      tags:
        - tarjeta
      summary: Eliminar tarjeta por su ID
      operationId: deleteCreditCardById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Tarjeta de credito eliminada
        'default':
          description: Error al eliminar la tarjeta
  /clientes:
    get:
      tags:
        - cliente
      summary: Listar clientes
      operationId: listCustomers.
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'
        'default':
          description: Error en la obtención de clientes
    post:
      tags:
        - cliente
      summary: Crear un cliente
      operationId: registerCustomer
      requestBody:
        description: Registrar un cliente
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerRequest"
      responses:
        '200':
          description: Cliente registrado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        default:
          description: Error en la creacion de cliente
  /clientes/{id}:
    get:
      tags:
        - cliente
      summary: Obtener datos de un cliente
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cliente obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        default:
          description: Error en obtener datos del cliente
    put:
      tags:
        - cliente
      summary: Actualizar un cliente
      operationId: updateCustomer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Detalles del cliente actualizada
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerRequest"
      responses:
        '200':
          description: Cliente actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        default:
          description: Error en la actualización de cliente
    delete:
      tags:
        - cliente
      summary: Eliminar cliente por su ID
      operationId: deleteCustomerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Cliente eliminado
        'default':
          description: Error al eliminar el cliente
  /cuentas:
    get:
      tags:
        - cuenta
      summary: Listar cuentas
      operationId: listAccounts.
      responses:
        '200':
          description: Lista de cuentas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResponse'
        'default':
          description: Error en la obtención de cuentas
    post:
      tags:
        - cuenta
      summary: Crear una cuenta
      operationId: registerAccount
      requestBody:
        description: Registrar una cuenta
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountRequest"
      responses:
        '200':
          description: Cuenta registrada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponse"
        default:
          description: Error en la creacion de cuenta
  /cuentas/{id}:
    get:
      tags:
        - cuenta
      summary: Obtener datos de una cuenta
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cuenta obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponse"
        default:
          description: Error en obtener datos de la cuenta
    put:
      tags:
        - cuenta
      summary: Actualizar una cuenta
      operationId: updateAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Detalles de la cuenta actualizada
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountRequest"
      responses:
        '200':
          description: Cuenta actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponse"
        default:
          description: Error en la actualización de cuenta
    delete:
      tags:
        - cuenta
      summary: Eliminar cuenta por su ID
      operationId: deleteAccountById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Cuenta eliminada
        'default':
          description: Error al eliminar la cuenta
components:
  schemas:
    CreditCardRequest:
      type: object
      properties:
        id:
          type: string
          description: ID único de la tarjeta de crédito
        cardNumber:
          type: string
          description: Número de la tarjeta de crédito
        accountHolder:
          type: string
          description: Titular de la cuenta
        balance:
          type: number
          description: Saldo disponible en la tarjeta
        creditLimit:
          type: number
          description: Límite de crédito disponible
    CreditCardResponse:
      type: object
      properties:
        id:
          type: string
          description: ID único de la tarjeta de crédito
        cardNumber:
          type: string
          description: Número de la tarjeta de crédito
        accountHolder:
          type: string
          description: Titular de la cuenta
        balance:
          type: number
          description: Saldo disponible en la tarjeta
        creditLimit:
          type: number
          description: Límite de crédito disponible
    CustomerRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único del cliente
        nombre:
          type: string
          description: Nombre del cliente
        apellido:
          type: string
          description: Apellido del cliente
        dni:
          type: string
          description: DNI del cliente
        email:
          type: string
          description: Email del cliente
    CustomerResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
          description: Nombre del cliente
        apellido:
          type: string
          description: Apellido del cliente
        dni:
          type: string
          description: DNI del cliente
        email:
          type: string
          description: Email del cliente
    AccountRequest:
      type: object
      properties:
        id:
          type: string
          description: ID único de la cuenta
        numeroCuenta:
          type: string
          description: Numero de la cuenta
        saldo:
          type: number
          format: double
          description: Saldo de la cuenta
        tipoCuenta:
          type: string
          description: Tipo de la cuenta
        clienteId:
          type: string
          description: ID del cliente de la cuenta
    AccountResponse:
      type: object
      properties:
        id:
          type: string
          description: ID único de la cuenta
        numeroCuenta:
          type: string
          description: Numero de la cuenta
        saldo:
          type: number
          format: double
          description: Saldo de la cuenta
        tipoCuenta:
          type: string
          description: Tipo de la cuenta
        clienteId:
          type: string
          description: ID del cliente de la cuenta